name: Check Formatting

on:
  merge_group:
  pull_request:
  push:
    branches: [main, development]

jobs:
  code-quality:
    name: ESLint & Prettier Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Prettier Check
      run: npm run format:check
      
    - name: ESLint Check
      run: npm run lint